### ISSUE TITLE
Provide option to tie installable version of `botocore` to that of `botocore-stubs`

### ISSUE THREAD

**Issue by jakob-keller** [youtype/botocore-stubs#6]
This request is inspired by the optional `boto3` extra offered by `boto3-stubs`. Selecting the extra sets a hard pin on the versions of `boto3` and `botocore`, effectively providing convenient synchronisation of those packages' installed versions:
`pip install boto3==1.28.60 boto3-stubs[boto3]` will install version 1.28.60 of both boto3 and boto3-stubs. Despite there being available a more recent version of boto3-stubs.

Such a simple mechanism might also be offered by `botocore-stubs`: A new extra named `botocore` would set a hard pin to the respective version of `botocore`.

**Comment by jakob-keller** [comment]
Here's how `pyproject.toml` would need to look like to make this work.

```toml
[tool.poetry.dependencies]
botocore = { version = "1.31.64", optional = true }
python = "^3.7"
types-awscrt = "*"
typing-extensions = { version = ">=4.1.0", python = "<3.9" }

[tool.poetry.extras]
botocore = [
    "botocore",
]
```

The actual botocore version would need to be bumped through `publish_on_update.yml`.
